# Copyright (c) 2022-2026 MKM Research Labs.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""Schema-contract tests for the Postgres relational models (WP1.2).

Pin the promoted-columns + JSONB-tail design so a model change is a deliberate,
visible edit. Pure metadata assertions — no live database. Model↔migration drift
is caught at docker time by ``alembic check`` (autogenerate shows no diff)."""

import pytest

from database._pg import (
    Base,
    Catchment,
    Commercial,
    CommercialLoan,
    Counterparty,
    EodSnapshot,
    Gauge,
    GaugeHazardCurve,
    Loan,
    PortRun,
    Property,
    PrsTrade,
)

# Every keyed entity → (model, composite-PK id column, table name).
_ENTITIES = [
    (Gauge, "gauge_id", "gauge"),
    (Property, "property_id", "property"),
    (Loan, "rloan_id", "loan"),
    (Commercial, "commercial_id", "commercial"),
    (CommercialLoan, "mortgage_id", "commercial_loan"),
    (Counterparty, "party_id", "counterparty"),
    (GaugeHazardCurve, "gauge_id", "gauge_hazard_curve"),
    (PrsTrade, "swap_id", "prs_trade"),
    (EodSnapshot, "eod_date", "eod_snapshot"),
]
# Generated by a port run (carry port_run_id); trading-desk EOD snapshots do not.
_GENERATED = [e for e in _ENTITIES if e[0] is not EodSnapshot]


def test_expected_tables_registered():
    assert set(Base.metadata.tables) == {
        "catchment", "port_run", "port_document", "port_record", "port_blob",
        "gauge", "property", "loan", "commercial", "commercial_loan", "counterparty",
        "gauge_hazard_curve", "prs_trade", "eod_snapshot",
        # WP5 RBAC tables (see test_pg_auth_models.py)
        "function", "app_user", "permission", "audit_log",
    }


@pytest.mark.parametrize("model,id_col,table", _ENTITIES)
def test_entity_shape(model, id_col, table):
    """Shared invariant: composite PK (catchment_id, <id>), a non-null cdm JSONB
    tail, and an FK to catchment."""
    assert model.__tablename__ == table
    assert {c.name for c in model.__table__.primary_key.columns} == {"catchment_id", id_col}
    assert model.__table__.c.cdm.nullable is False
    fk_targets = {fk.column.table.name for fk in model.__table__.foreign_keys}
    assert "catchment" in fk_targets


@pytest.mark.parametrize("model,id_col,table", _GENERATED)
def test_generated_entities_reference_port_run(model, id_col, table):
    fk_targets = {fk.column.table.name for fk in model.__table__.foreign_keys}
    assert "port_run" in fk_targets


def test_gauge_promoted_columns_and_cdm():
    cols = {c.name for c in Gauge.__table__.columns}
    assert cols == {
        "catchment_id", "gauge_id", "port_run_id", "gauge_name",
        "latitude", "longitude", "elevation",
        "flood_alert", "flood_warning", "severe_flood_warning",
        "nrfa_station_id", "cdm",
    }
    # Full document preserved + non-null for round-trip fidelity.
    assert Gauge.__table__.c.cdm.nullable is False


def test_gauge_composite_primary_key():
    pk = {c.name for c in Gauge.__table__.primary_key.columns}
    assert pk == {"catchment_id", "gauge_id"}  # gauge ids repeat across catchments


def test_gauge_foreign_keys():
    fks = {
        (fk.parent.name, fk.column.table.name)
        for fk in Gauge.__table__.foreign_keys
    }
    assert ("catchment_id", "catchment") in fks
    assert ("port_run_id", "port_run") in fks


def test_property_promoted_columns_and_cdm():
    cols = {c.name for c in Property.__table__.columns}
    assert cols == {
        "catchment_id", "property_id", "port_run_id", "uprn", "property_type",
        "status", "property_value", "latitude", "longitude", "postcode",
        "town_city", "local_authority", "area_sqm", "construction_year",
        "ea_flood_zone", "overall_flood_risk", "cdm",
    }
    assert Property.__table__.c.cdm.nullable is False
    assert {c.name for c in Property.__table__.primary_key.columns} == {
        "catchment_id", "property_id",
    }


def test_port_run_provenance_columns():
    cols = {c.name for c in PortRun.__table__.columns}
    assert cols == {
        "id", "catchment_id", "artifact", "mode",
        "generated_at", "schema_version", "generation_metadata",
    }
    assert {c.name for c in PortRun.__table__.primary_key.columns} == {"id"}


def test_catchment_is_the_fk_anchor():
    assert {c.name for c in Catchment.__table__.primary_key.columns} == {"id"}
