# Copyright (c) 2022-2026 MKM Research Labs. All rights reserved.
#
# Use, reproduction, distribution, or modification of this code is subject to the
# terms and conditions of the license agreement provided with this software.

"""PDF assembly and entry point for the data lineage report."""

from pathlib import Path

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.platypus import PageBreak, Paragraph, SimpleDocTemplate

from .collect import collect_all
from .styles import _styles, _section_rule
from .sections_summary import (
    _build_cover, _build_exec_summary, _build_topology, _build_quality_metrics,
)
from .sections_recon import _build_reconciliation, _build_source_documentation
from .sections_policy import _build_retention_policy, _build_remediation


def create_pdf_report(data: dict = None) -> Path:
    """Build the full data lineage report PDF."""
    import docs.models.data_lineage as pkg

    if data is None:
        data = collect_all()

    pkg.AUDIT_DIR.mkdir(parents=True, exist_ok=True)

    doc = SimpleDocTemplate(
        str(pkg.OUTPUT_PDF),
        pagesize=A4,
        rightMargin=0.6 * inch,
        leftMargin=0.6 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.6 * inch,
    )
    S = _styles()
    story = []

    # Cover
    _build_cover(data, story, S)
    story.append(PageBreak())

    # 1. Executive Summary
    _build_exec_summary(data, story, S)
    story.append(PageBreak())

    # 2. Pipeline Topology & Upstream Dependencies
    _build_topology(data, story, S)
    story.append(PageBreak())

    # 3. Data Quality Metrics
    _build_quality_metrics(data, story, S)
    story.append(PageBreak())

    # 4. Data Reconciliation Procedures
    _build_reconciliation(data, story, S)
    story.append(PageBreak())

    # 5. Data Source Documentation
    _build_source_documentation(data, story, S)
    story.append(PageBreak())

    # 6. Data Retention Policy
    _build_retention_policy(data, story, S)
    story.append(PageBreak())

    # 7. Remediation
    _build_remediation(data, story, S)

    # Footer
    _section_rule(story)
    story.append(Paragraph(
        f"<i>Report generated by docs.models.data_lineage — "
        f"MKM Research Labs Physical Risk Platform</i>",
        S['small']))

    doc.build(story)
    return pkg.OUTPUT_PDF


def main():
    import docs.models.data_lineage as pkg

    print("Generating Data Lineage Report (BCBS 239)...")
    data = pkg.collect_all()
    print(f"  {data['num_steps']} pipeline steps, "
          f"{data['num_recorded']} recorded")
    chain = data['chain_result']
    print(f"  Consistency: "
          f"{'OK' if chain['is_consistent'] else 'ISSUES FOUND'}")
    if chain.get('stale_steps'):
        print(f"  Stale steps: {', '.join(chain['stale_steps'])}")
    if chain.get('missing_steps'):
        print(f"  Missing steps: {', '.join(chain['missing_steps'])}")

    out = pkg.create_pdf_report(data)
    size_kb = out.stat().st_size / 1024
    print(f"  data_lineage_report.pdf written to {out}  ({size_kb:.1f} KB)")
