"""
app.py classifier -- Train or inspect flood classifiers.

Reads per-gauge vector files from stress_vectors/ (generated by
port step 5b) and trains GBM classifiers to stressm/.

Progress notifications:
  - Per-gauge progress bar with ETA derived from historical timings
  - Final elapsed time printed and saved to classifier_timings.json
  - Subsequent runs use the saved average to estimate completion

Usage:
    python3 app.py classifier                         # train Westminster Bridge (default)
    python3 app.py classifier GAUGE-066fc60e          # train one gauge
    python3 app.py classifier GAUGE-066fc60e GAUGE-085522ee  # train several
    python3 app.py classifier --all                   # train all gauges
    python3 app.py classifier --list                  # list available gauges
"""

import json
import time
from pathlib import Path

from config import config


_TIMINGS_FILENAME = "classifier_timings.json"


def register_parser(subparsers):
    sp = subparsers.add_parser("classifier", help="Train GBM flood classifiers")
    sp.add_argument("gauge_ids", nargs="*", metavar="GAUGE-ID",
                    help="One or more gauge IDs to train")
    sp.add_argument("--all", "-a", action="store_true",
                    help="Train all gauges with saved vectors")
    sp.add_argument("--list", "-l", action="store_true", dest="list_gauges",
                    help="List gauge IDs with saved vectors")
    sp.set_defaults(func=run)


def _load_timings(stressm_dir: Path) -> dict:
    """Load historical classifier training timings."""
    path = stressm_dir / _TIMINGS_FILENAME
    if path.exists():
        try:
            with open(path) as f:
                return json.load(f)
        except Exception:
            pass
    return {"runs": []}


def _save_timings(stressm_dir: Path, timings: dict) -> None:
    """Save classifier training timings (keep last 20 runs)."""
    timings["runs"] = timings["runs"][-20:]
    path = stressm_dir / _TIMINGS_FILENAME
    with open(path, "w") as f:
        json.dump(timings, f, indent=2)


def _avg_per_gauge_seconds(timings: dict) -> float:
    """Return average seconds per gauge from historical runs, or 0 if none."""
    runs = timings.get("runs", [])
    if not runs:
        return 0.0
    total_time = sum(r.get("elapsed_seconds", 0) for r in runs)
    total_gauges = sum(r.get("num_gauges", 1) for r in runs)
    return total_time / max(total_gauges, 1)


def _format_eta(seconds: float) -> str:
    """Format seconds as human-readable ETA."""
    if seconds < 60:
        return f"{seconds:.0f}s"
    if seconds < 3600:
        return f"{seconds / 60:.1f}m"
    return f"{seconds / 3600:.1f}h"


def _progress_line(i: int, total: int, gid: str, elapsed: float,
                   avg_per_gauge: float) -> str:
    """Build a progress line with percentage and ETA."""
    pct = (i + 1) / total * 100
    parts = [f"  [{i + 1}/{total}] ({pct:4.1f}%)  {gid}"]
    if avg_per_gauge > 0:
        remaining = (total - i - 1) * avg_per_gauge
        parts.append(f"  ETA {_format_eta(remaining)}")
    elif i > 0 and elapsed > 0:
        per_gauge = elapsed / i
        remaining = (total - i - 1) * per_gauge
        parts.append(f"  ETA {_format_eta(remaining)}")
    return "".join(parts)


def run(args):
    from models.stress.flood_classifier import FloodClassifierTrainer

    from port.src.stress_vectors import load_gauge_vectors, list_available_gauges

    sv_dir = config.get_stress_vectors_dir()
    stressm_dir = config.get_stressm_dir()

    # Find all saved vector files (chunked or legacy)
    available_ids = list_available_gauges(sv_dir)
    available = {gid: sv_dir for gid in available_ids}

    if not available:
        print(f"No stress vectors in {sv_dir}")
        print("  Run 'python3 app.py port' or 'python3 app.py port --sv' first.")
        return

    if args.list_gauges:
        print(f"{len(available)} gauges with stress vectors:\n")
        for gid in sorted(available):
            data = load_gauge_vectors(sv_dir, gid)
            n = data.get("num_vectors", len(data.get("vector", [])))
            rate = data.get("flood_rate", 0)
            label = data.get("label_threshold", "?")
            print(f"  {gid}  ({n:,} vectors, {rate:.1%} flood, {label})")
        return

    DEFAULT_GAUGE = "GAUGE-a6be4ee9"  # Thames Westminster Bridge

    if args.all:
        ids = sorted(available)
    elif args.gauge_ids:
        ids = args.gauge_ids
    else:
        ids = [DEFAULT_GAUGE]
        print(f"No gauge specified, using default: {DEFAULT_GAUGE} (Westminster Bridge)\n")

    # Validate
    missing = [gid for gid in ids if gid not in available]
    if missing:
        print(f"No stress vectors for: {', '.join(missing)}")
        print(f"  Available: {', '.join(sorted(available)[:5])}...")
        return

    total = len(ids)
    print(f"Training {total} classifier{'s' if total != 1 else ''}...\n")

    # Load historical timings for ETA
    timings = _load_timings(stressm_dir)
    avg_per_gauge = _avg_per_gauge_seconds(timings)
    if avg_per_gauge > 0 and total > 1:
        est = _format_eta(avg_per_gauge * total)
        print(f"  Estimated time: {est} (based on {len(timings['runs'])} previous runs)\n")

    trainer = FloodClassifierTrainer(Path("_unused"), stressm_dir)
    trained = 0
    clf_results = []
    t_start = time.time()

    for i, gid in enumerate(ids):
        t_gauge = time.time()

        # Progress header
        if total > 1:
            elapsed_so_far = time.time() - t_start
            print(_progress_line(i, total, gid, elapsed_so_far, avg_per_gauge),
                  flush=True)

        # Load vectors (reassembles chunks)
        gauge_data = load_gauge_vectors(sv_dir, gid)
        n_vectors = len(gauge_data.get("vector", []))
        print(f"    Loading {n_vectors:,} vectors...", end="", flush=True)

        result = trainer.train_gauge(gid, gauge_data)
        gauge_elapsed = time.time() - t_gauge

        if result["status"] == "trained":
            m = result["metrics"]
            print(f"\r  {gid}:  AUC {m['auc_roc']:.4f}  Acc {m['accuracy']:.4f}  "
                  f"Brier {m['brier_score']:.4f}  "
                  f"rate={result['flood_rate']:.1%}  n={result['n_samples']:,}"
                  f"  ({gauge_elapsed:.1f}s)")
            trained += 1
            clf_results.append(result)
        else:
            print(f"\r  {gid}:  skipped -- {result.get('reason', 'unknown')}"
                  f"  ({gauge_elapsed:.1f}s)")

    # Write training summary
    if clf_results:
        from port.src.stressm.gaugets_writer import write_classifier_summary
        write_classifier_summary(clf_results)

    elapsed_total = time.time() - t_start

    # Save timing for future ETA estimates
    timings["runs"].append({
        "num_gauges": total,
        "num_trained": trained,
        "elapsed_seconds": round(elapsed_total, 2),
        "avg_per_gauge_seconds": round(elapsed_total / max(total, 1), 2),
    })
    _save_timings(stressm_dir, timings)

    print(f"\nDone. {trained}/{total} trained "
          f"({_format_eta(elapsed_total)}) "
          f"-> {stressm_dir}")
