# Copyright (c) 2022-2026 MKM Research Labs.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""PDF assembly and CLI entry point for the model risk governance report."""

from collections import Counter
from pathlib import Path

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.platypus import PageBreak, Paragraph, SimpleDocTemplate

from .data import AUDIT_DIR, OUTPUT_PDF, collect_all
from .styles import get_styles, section_rule
from .sections import (
    build_cover,
    build_exec_summary,
    build_model_inventory,
    build_validation_status,
    build_mrc_activity,
    build_remediation,
    build_bcbs239,
    build_raci,
    build_test_evidence,
    build_audit_trail,
    build_document_inventory,
    build_recommendations,
)


def create_pdf_report(data: dict = None) -> Path:
    """Build the full model risk governance PDF."""
    if data is None:
        data = collect_all()

    AUDIT_DIR.mkdir(parents=True, exist_ok=True)

    doc = SimpleDocTemplate(
        str(OUTPUT_PDF),
        pagesize=A4,
        rightMargin=0.55 * inch,
        leftMargin=0.55 * inch,
        topMargin=0.7 * inch,
        bottomMargin=0.55 * inch,
    )
    S = get_styles()
    story = []

    build_cover(data, story, S)
    story.append(PageBreak())
    build_exec_summary(data, story, S)
    story.append(PageBreak())
    build_model_inventory(data, story, S)
    story.append(PageBreak())
    build_validation_status(data, story, S)
    story.append(PageBreak())
    build_mrc_activity(data, story, S)
    story.append(PageBreak())
    build_remediation(data, story, S)
    story.append(PageBreak())
    build_bcbs239(data, story, S)
    story.append(PageBreak())
    build_raci(data, story, S)
    story.append(PageBreak())
    build_test_evidence(data, story, S)
    story.append(PageBreak())
    build_audit_trail(data, story, S)
    story.append(PageBreak())
    build_document_inventory(data, story, S)
    story.append(PageBreak())
    build_recommendations(data, story, S)

    section_rule(story)
    story.append(Paragraph(
        "<i>Report generated by docs.models.model_risk — "
        "MKM Research Labs Physical Risk Platform</i>",
        S['small']))

    doc.build(story)
    return OUTPUT_PDF


def main():
    """CLI entry point — collect data, print summary, generate PDF."""
    print("Generating Model Risk Governance Report...")
    data = collect_all()
    models = data['models']
    print(f"  {len(models)} models in inventory")
    rags = Counter(m.get('rag_rating', '?') for m in models)
    print(f"  RAG: Green={rags.get('Green', 0)} "
          f"Amber={rags.get('Amber', 0)} Red={rags.get('Red', 0)}")
    total_rems = sum(len(m.get('remediation_steps', [])) for m in models)
    print(f"  {total_rems} remediation items")
    print(f"  {len(data['meetings'])} MRC meetings")
    print(f"  {len(data['audit_log'])} audit trail events")

    out = create_pdf_report(data)
    size_kb = out.stat().st_size / 1024
    print(f"  model_risk_report.pdf written to {out}  ({size_kb:.1f} KB)")
