# Copyright (c) 2022-2026 MKM Research Labs.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""Shared sensitivity analysis utilities."""

import os


def latex_table(caption, label, headers, rows, col_fmt=None):
    """Build a LaTeX table string."""
    n = len(headers)
    if col_fmt is None:
        col_fmt = 'r' * n
    lines = [
        r'\begin{table}[H]',
        r'    \centering',
        f'    \\caption{{{caption}}}',
        f'    \\label{{tab:{label}}}',
        f'    \\begin{{tabular}}{{{col_fmt}}}',
        r'        \toprule',
        '        ' + ' & '.join(rf'\textbf{{{h}}}' for h in headers) + r' \\',
        r'        \midrule',
    ]
    for row in rows:
        cells = []
        for v in row:
            if isinstance(v, float):
                if abs(v) >= 1000:
                    cells.append(f'{v:,.1f}'.replace(',', r'{,}'))
                elif abs(v) >= 10:
                    cells.append(f'{v:.1f}')
                elif abs(v) >= 1:
                    cells.append(f'{v:.2f}')
                else:
                    cells.append(f'{v:.4f}')
            elif isinstance(v, int):
                cells.append(str(v))
            else:
                cells.append(str(v))
        lines.append('        ' + ' & '.join(cells) + r' \\')
    lines += [
        r'        \bottomrule',
        r'    \end{tabular}',
        r'\end{table}',
    ]
    return '\n'.join(lines)


def write_tables(model_dir, content):
    """Write LaTeX fragment to model directory."""
    from config import config
    _docs_models = config.get_project_root() / 'docs' / 'models'
    path = os.path.join(_docs_models, model_dir, 'sensitivity_tables.tex')
    with open(path, 'w') as f:
        f.write('% Auto-generated by sensitivity generator\n')
        f.write('% Do not edit manually --- regenerate with: '
                'python -m docs.models.sensitivities.generate_all\n\n')
        f.write(content)
    print(f'  Written: {path}')
