# Copyright (c) 2022-2026 MKM Research Labs. All rights reserved.

# This software is licensed by MKM Research Labs for non-commercial 
# research and educational use only. Any commercial use, including 
# but not limited to use in or for products or services offered for sale, 
# internal business operations intended for commercial advantage, or
# research and development conducted for a commercial entity, is expressly
# prohibited unless separately authorized in writing by MKM Research Labs.

# Use, reproduction, distribution, or modification of this code is subject to the
# terms and conditions of the license agreement provided with this software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""Shared sensitivity analysis utilities."""

import os


def latex_table(caption, label, headers, rows, col_fmt=None):
    """Build a LaTeX table string."""
    n = len(headers)
    if col_fmt is None:
        col_fmt = 'r' * n
    lines = [
        r'\begin{table}[H]',
        r'    \centering',
        f'    \\caption{{{caption}}}',
        f'    \\label{{tab:{label}}}',
        f'    \\begin{{tabular}}{{{col_fmt}}}',
        r'        \toprule',
        '        ' + ' & '.join(rf'\textbf{{{h}}}' for h in headers) + r' \\',
        r'        \midrule',
    ]
    for row in rows:
        cells = []
        for v in row:
            if isinstance(v, float):
                if abs(v) >= 1000:
                    cells.append(f'{v:,.1f}'.replace(',', r'{,}'))
                elif abs(v) >= 10:
                    cells.append(f'{v:.1f}')
                elif abs(v) >= 1:
                    cells.append(f'{v:.2f}')
                else:
                    cells.append(f'{v:.4f}')
            elif isinstance(v, int):
                cells.append(str(v))
            else:
                cells.append(str(v))
        lines.append('        ' + ' & '.join(cells) + r' \\')
    lines += [
        r'        \bottomrule',
        r'    \end{tabular}',
        r'\end{table}',
    ]
    return '\n'.join(lines)


def write_tables(model_dir, content):
    """Write LaTeX fragment to model directory."""
    _docs_models = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
    path = os.path.join(_docs_models, model_dir, 'sensitivity_tables.tex')
    with open(path, 'w') as f:
        f.write('% Auto-generated by sensitivity generator\n')
        f.write('% Do not edit manually --- regenerate with: '
                'python -m docs.models.sensitivities.generate_all\n\n')
        f.write(content)
    print(f'  Written: {path}')
