#!/usr/bin/env bash
# Run the suite against a throwaway thames portfolio, then delete it.
#
# Usage: scripts/test-ephemeral.sh [phys.py test args...]
#   scripts/test-ephemeral.sh --unit
#   scripts/test-ephemeral.sh --all --audit
#
# Why a script rather than a `phys.py test --ephemeral` flag: MKM_DATA_ROOT is
# read when PortfolioConfig is constructed, which happens at config import time
# — so by the time any Python entry point could set it, it is already too late,
# and with the real data volume detached that import is exactly what crashes.
# The environment has to be set before the interpreter starts, so generation
# and testing run as child processes of this shell.
#
# The portfolio is generated with a fixed --seed, so a failing run can be
# reproduced by re-running the same command.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$HERE/.." && pwd)"

# Size of the throwaway portfolio. Small enough to generate quickly, large
# enough to satisfy the checks that need a real gauge set.
NUM_GAUGES="${MKM_EPH_GAUGES:-10}"
NUM_PROPERTIES="${MKM_EPH_PROPERTIES:-1}"
NUM_COMMERCIAL="${MKM_EPH_COMMERCIAL:-1}"
NUM_SIMS="${MKM_EPH_SIMS:-100}"
SEED="${MKM_EPH_SEED:-1}"
CATCHMENT="${MKM_CATCHMENT:-thames}"

PREFIX="${TMPDIR:-/tmp}/pr-ephemeral"

# --- Sweep roots left by an interrupted run --------------------------------
# A SIGKILL skips the trap below, so a previous run can leave a tree behind.
# Anything older than six hours cannot belong to a live run.
sweep_stale() {
  find "$(dirname "$PREFIX")" -maxdepth 1 -name "$(basename "$PREFIX")-*" \
       -type d -mmin +360 -print0 2>/dev/null |
    while IFS= read -r -d '' old; do
      echo "  sweeping stale root: $old"
      rm -rf "$old"
    done
}

# Sweep first: a run that cannot proceed should still clear debris.
sweep_stale

# --- Preflight -------------------------------------------------------------
# The venv must be active. Without it `python` resolves to whatever is on PATH,
# which here fails deep inside SQLAlchemy on Python 3.13 with an assertion
# about TypingOnly — twenty seconds in and nothing to do with this script.
if ! python -c "import sys; sys.exit(0 if sys.prefix.startswith(sys.argv[1]) else 1)" \
       "$REPO/.venv" 2>/dev/null; then
  echo "ERROR: the repo virtualenv is not active." >&2
  echo "  Run: source .venv/bin/activate" >&2
  exit 2
fi

# Catchment parameters are generation INPUTS. They are Python modules imported
# as `catch.<id>`, resolved from the repo's catch/ package or the data root.
# Without them `port` fails partway, after doing real work — check up front.
if [ ! -e "$REPO/catch/$CATCHMENT.py" ] && [ ! -d "$REPO/catch/$CATCHMENT" ]; then
  if [ ! -e "$REPO/data/catch/$CATCHMENT.py" ] && [ ! -d "$REPO/data/catch/$CATCHMENT" ]; then
    echo "ERROR: no parameters for catchment '$CATCHMENT'." >&2
    echo "  Looked in: $REPO/catch/  and  $REPO/data/catch/" >&2
    echo "  Vendor them into catch/ — see catch/README.md — or attach the" >&2
    echo "  data volume. They cannot be generated; they are an input." >&2
    exit 2
  fi
  echo "note: using catchment parameters from data/catch/ (not yet vendored)"
fi

# `port` is behind an admin-password gate. The credential lives beside the
# portfolio (<data root>/.port_admin), so a throwaway root always starts
# without one and takes the first-run setup branch. Supplying a value here
# lets that branch run unattended — the point of the gate is to stop an
# accidental overwrite of the shared tree, and this root is a fresh temp
# directory deleted a few minutes from now. A caller who exports their own
# value keeps it.
export MKM_PORT_ADMIN_PASSWORD="${MKM_PORT_ADMIN_PASSWORD:-throwaway-portfolio}"

DATA_ROOT="$(mktemp -d "${PREFIX}-XXXXXX")"

# EXIT covers success, failure and `set -e`; INT/TERM cover Ctrl-C and kill.
# Only SIGKILL escapes, which is what sweep_stale exists for.
cleanup() {
  local rc=$?
  if [ "${MKM_EPH_KEEP:-}" = "1" ]; then
    echo "MKM_EPH_KEEP=1 — leaving $DATA_ROOT in place"
  else
    echo "removing throwaway portfolio: $DATA_ROOT"
    rm -rf "$DATA_ROOT"
  fi
  exit "$rc"
}
trap cleanup EXIT INT TERM

export MKM_DATA_ROOT="$DATA_ROOT"

echo "=============================================================="
echo " Throwaway portfolio"
echo "=============================================================="
echo " Root       : $DATA_ROOT"
echo " Catchment  : $CATCHMENT"
echo " Size       : ${NUM_GAUGES} gauges, ${NUM_PROPERTIES} properties,"
echo "              ${NUM_COMMERCIAL} commercial, ${NUM_SIMS} sims"
echo " Seed       : $SEED  (re-run this command to reproduce)"
echo

cd "$REPO"
python phys.py port "--$CATCHMENT" \
  -ng "$NUM_GAUGES" -np "$NUM_PROPERTIES" -nc "$NUM_COMMERCIAL" \
  -ns "$NUM_SIMS" --seed "$SEED"

echo
echo " Generated: $(du -sh "$DATA_ROOT" | cut -f1)"
echo

# Tells the suite the portfolio was generated by this run, so checks that
# compare recorded state against current files skip rather than pass
# tautologically. See tests/_dataset.py.
export MKM_EPHEMERAL_DATASET=1

python phys.py test "$@"
