# Copyright (c) 2022-2026 MKM Research Labs.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""create loan commercial commercial_loan counterparty tables

Revision ID: 61313894caf0
Revises: e756b1c4f89e
Create Date: 2026-06-22 12:01:28.270063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61313894caf0'
down_revision: Union[str, None] = 'e756b1c4f89e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commercial',
    sa.Column('catchment_id', sa.String(), nullable=False),
    sa.Column('commercial_id', sa.String(), nullable=False),
    sa.Column('port_run_id', sa.Integer(), nullable=True),
    sa.Column('uprn', sa.String(), nullable=True),
    sa.Column('property_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('property_value', sa.Float(), nullable=True),
    sa.Column('cdm', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['catchment_id'], ['catchment.id'], ),
    sa.ForeignKeyConstraint(['port_run_id'], ['port_run.id'], ),
    sa.PrimaryKeyConstraint('catchment_id', 'commercial_id')
    )
    op.create_index(op.f('ix_commercial_port_run_id'), 'commercial', ['port_run_id'], unique=False)
    op.create_index(op.f('ix_commercial_property_type'), 'commercial', ['property_type'], unique=False)
    op.create_table('commercial_loan',
    sa.Column('catchment_id', sa.String(), nullable=False),
    sa.Column('mortgage_id', sa.String(), nullable=False),
    sa.Column('port_run_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.String(), nullable=True),
    sa.Column('uprn', sa.String(), nullable=True),
    sa.Column('borrower_type', sa.String(), nullable=True),
    sa.Column('commercial_type', sa.String(), nullable=True),
    sa.Column('cdm', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['catchment_id'], ['catchment.id'], ),
    sa.ForeignKeyConstraint(['port_run_id'], ['port_run.id'], ),
    sa.PrimaryKeyConstraint('catchment_id', 'mortgage_id')
    )
    op.create_index(op.f('ix_commercial_loan_commercial_type'), 'commercial_loan', ['commercial_type'], unique=False)
    op.create_index(op.f('ix_commercial_loan_port_run_id'), 'commercial_loan', ['port_run_id'], unique=False)
    op.create_index(op.f('ix_commercial_loan_property_id'), 'commercial_loan', ['property_id'], unique=False)
    op.create_table('counterparty',
    sa.Column('catchment_id', sa.String(), nullable=False),
    sa.Column('party_id', sa.String(), nullable=False),
    sa.Column('port_run_id', sa.Integer(), nullable=True),
    sa.Column('party_name', sa.String(), nullable=True),
    sa.Column('party_id_scheme', sa.String(), nullable=True),
    sa.Column('cdm', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['catchment_id'], ['catchment.id'], ),
    sa.ForeignKeyConstraint(['port_run_id'], ['port_run.id'], ),
    sa.PrimaryKeyConstraint('catchment_id', 'party_id')
    )
    op.create_index(op.f('ix_counterparty_party_name'), 'counterparty', ['party_name'], unique=False)
    op.create_index(op.f('ix_counterparty_port_run_id'), 'counterparty', ['port_run_id'], unique=False)
    op.create_table('loan',
    sa.Column('catchment_id', sa.String(), nullable=False),
    sa.Column('rloan_id', sa.String(), nullable=False),
    sa.Column('port_run_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.String(), nullable=True),
    sa.Column('uprn', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('original_loan', sa.Float(), nullable=True),
    sa.Column('original_ltv', sa.Float(), nullable=True),
    sa.Column('outstanding_balance', sa.Float(), nullable=True),
    sa.Column('current_ltv', sa.Float(), nullable=True),
    sa.Column('account_status', sa.String(), nullable=True),
    sa.Column('default_flag', sa.Boolean(), nullable=True),
    sa.Column('arrears_months', sa.Integer(), nullable=True),
    sa.Column('cdm', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['catchment_id'], ['catchment.id'], ),
    sa.ForeignKeyConstraint(['port_run_id'], ['port_run.id'], ),
    sa.PrimaryKeyConstraint('catchment_id', 'rloan_id')
    )
    op.create_index(op.f('ix_loan_account_status'), 'loan', ['account_status'], unique=False)
    op.create_index(op.f('ix_loan_port_run_id'), 'loan', ['port_run_id'], unique=False)
    op.create_index(op.f('ix_loan_property_id'), 'loan', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loan_property_id'), table_name='loan')
    op.drop_index(op.f('ix_loan_port_run_id'), table_name='loan')
    op.drop_index(op.f('ix_loan_account_status'), table_name='loan')
    op.drop_table('loan')
    op.drop_index(op.f('ix_counterparty_port_run_id'), table_name='counterparty')
    op.drop_index(op.f('ix_counterparty_party_name'), table_name='counterparty')
    op.drop_table('counterparty')
    op.drop_index(op.f('ix_commercial_loan_property_id'), table_name='commercial_loan')
    op.drop_index(op.f('ix_commercial_loan_port_run_id'), table_name='commercial_loan')
    op.drop_index(op.f('ix_commercial_loan_commercial_type'), table_name='commercial_loan')
    op.drop_table('commercial_loan')
    op.drop_index(op.f('ix_commercial_property_type'), table_name='commercial')
    op.drop_index(op.f('ix_commercial_port_run_id'), table_name='commercial')
    op.drop_table('commercial')
    # ### end Alembic commands ###
