# Copyright (c) 2022-2026 MKM Research Labs. All rights reserved.

# This software is licensed by MKM Research Labs for non-commercial
# research and educational use only. Any commercial use, including
# but not limited to use in or for products or services offered for sale,
# internal business operations intended for commercial advantage, or
# research and development conducted for a commercial entity, is expressly
# prohibited unless separately authorized in writing by MKM Research Labs.

# Use, reproduction, distribution, or modification of this code is subject to the
# terms and conditions of the license agreement provided with this software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""create gauge_hazard_curve prs_trade eod_snapshot tables

Revision ID: cb463f03ebec
Revises: 61313894caf0
Create Date: 2026-06-22 12:13:34.960490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb463f03ebec'
down_revision: Union[str, None] = '61313894caf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eod_snapshot',
    sa.Column('catchment_id', sa.String(), nullable=False),
    sa.Column('eod_date', sa.String(), nullable=False),
    sa.Column('eod_id', sa.String(), nullable=True),
    sa.Column('generated_at', sa.String(), nullable=True),
    sa.Column('num_open_trades', sa.Integer(), nullable=True),
    sa.Column('total_notional', sa.Float(), nullable=True),
    sa.Column('total_daily_pnl', sa.Float(), nullable=True),
    sa.Column('total_running_pnl', sa.Float(), nullable=True),
    sa.Column('cdm', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['catchment_id'], ['catchment.id'], ),
    sa.PrimaryKeyConstraint('catchment_id', 'eod_date')
    )
    op.create_table('gauge_hazard_curve',
    sa.Column('catchment_id', sa.String(), nullable=False),
    sa.Column('gauge_id', sa.String(), nullable=False),
    sa.Column('port_run_id', sa.Integer(), nullable=True),
    sa.Column('gauge_name', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('gev_location', sa.Float(), nullable=True),
    sa.Column('gev_scale', sa.Float(), nullable=True),
    sa.Column('gev_shape', sa.Float(), nullable=True),
    sa.Column('annual_hazard_rate_alert', sa.Float(), nullable=True),
    sa.Column('annual_hazard_rate_warning', sa.Float(), nullable=True),
    sa.Column('annual_hazard_rate_severe', sa.Float(), nullable=True),
    sa.Column('cdm', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['catchment_id'], ['catchment.id'], ),
    sa.ForeignKeyConstraint(['port_run_id'], ['port_run.id'], ),
    sa.PrimaryKeyConstraint('catchment_id', 'gauge_id')
    )
    op.create_index(op.f('ix_gauge_hazard_curve_port_run_id'), 'gauge_hazard_curve', ['port_run_id'], unique=False)
    op.create_table('prs_trade',
    sa.Column('catchment_id', sa.String(), nullable=False),
    sa.Column('swap_id', sa.String(), nullable=False),
    sa.Column('port_run_id', sa.Integer(), nullable=True),
    sa.Column('trade_type', sa.String(), nullable=True),
    sa.Column('counterparty', sa.String(), nullable=True),
    sa.Column('party_id', sa.String(), nullable=True),
    sa.Column('trade_status', sa.String(), nullable=True),
    sa.Column('valuation_date', sa.String(), nullable=True),
    sa.Column('notional', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('spread_bps', sa.Float(), nullable=True),
    sa.Column('npv', sa.Float(), nullable=True),
    sa.Column('trigger_level', sa.String(), nullable=True),
    sa.Column('cdm', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['catchment_id'], ['catchment.id'], ),
    sa.ForeignKeyConstraint(['port_run_id'], ['port_run.id'], ),
    sa.PrimaryKeyConstraint('catchment_id', 'swap_id')
    )
    op.create_index(op.f('ix_prs_trade_counterparty'), 'prs_trade', ['counterparty'], unique=False)
    op.create_index(op.f('ix_prs_trade_party_id'), 'prs_trade', ['party_id'], unique=False)
    op.create_index(op.f('ix_prs_trade_port_run_id'), 'prs_trade', ['port_run_id'], unique=False)
    op.create_index(op.f('ix_prs_trade_trade_status'), 'prs_trade', ['trade_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prs_trade_trade_status'), table_name='prs_trade')
    op.drop_index(op.f('ix_prs_trade_port_run_id'), table_name='prs_trade')
    op.drop_index(op.f('ix_prs_trade_party_id'), table_name='prs_trade')
    op.drop_index(op.f('ix_prs_trade_counterparty'), table_name='prs_trade')
    op.drop_table('prs_trade')
    op.drop_index(op.f('ix_gauge_hazard_curve_port_run_id'), table_name='gauge_hazard_curve')
    op.drop_table('gauge_hazard_curve')
    op.drop_table('eod_snapshot')
    # ### end Alembic commands ###
