# Copyright (c) 2022-2026 MKM Research Labs. All rights reserved.

# This software is licensed by MKM Research Labs for non-commercial
# research and educational use only. Any commercial use, including
# but not limited to use in or for products or services offered for sale,
# internal business operations intended for commercial advantage, or
# research and development conducted for a commercial entity, is expressly
# prohibited unless separately authorized in writing by MKM Research Labs.

# Use, reproduction, distribution, or modification of this code is subject to the
# terms and conditions of the license agreement provided with this software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""create property table

Revision ID: e756b1c4f89e
Revises: 5e2ff33a6b56
Create Date: 2026-06-22 11:40:17.878829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e756b1c4f89e'
down_revision: Union[str, None] = '5e2ff33a6b56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property',
    sa.Column('catchment_id', sa.String(), nullable=False),
    sa.Column('property_id', sa.String(), nullable=False),
    sa.Column('port_run_id', sa.Integer(), nullable=True),
    sa.Column('uprn', sa.String(), nullable=True),
    sa.Column('property_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('property_value', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('postcode', sa.String(), nullable=True),
    sa.Column('town_city', sa.String(), nullable=True),
    sa.Column('local_authority', sa.String(), nullable=True),
    sa.Column('area_sqm', sa.Float(), nullable=True),
    sa.Column('construction_year', sa.Integer(), nullable=True),
    sa.Column('ea_flood_zone', sa.String(), nullable=True),
    sa.Column('overall_flood_risk', sa.String(), nullable=True),
    sa.Column('cdm', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['catchment_id'], ['catchment.id'], ),
    sa.ForeignKeyConstraint(['port_run_id'], ['port_run.id'], ),
    sa.PrimaryKeyConstraint('catchment_id', 'property_id')
    )
    op.create_index(op.f('ix_property_ea_flood_zone'), 'property', ['ea_flood_zone'], unique=False)
    op.create_index(op.f('ix_property_port_run_id'), 'property', ['port_run_id'], unique=False)
    op.create_index(op.f('ix_property_postcode'), 'property', ['postcode'], unique=False)
    op.create_index(op.f('ix_property_property_type'), 'property', ['property_type'], unique=False)
    op.create_index(op.f('ix_property_uprn'), 'property', ['uprn'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_uprn'), table_name='property')
    op.drop_index(op.f('ix_property_property_type'), table_name='property')
    op.drop_index(op.f('ix_property_postcode'), table_name='property')
    op.drop_index(op.f('ix_property_port_run_id'), table_name='property')
    op.drop_index(op.f('ix_property_ea_flood_zone'), table_name='property')
    op.drop_table('property')
    # ### end Alembic commands ###
